/**
 * Стартовая библиотека фраз для Мираса (раздел 19 PRD).
 * Категории соответствуют списку категорий библиотеки фраз.
 */
export interface SeedPhrase {
  english: string;
  russian: string;
  category: string;
  cefrLevel: 'A1' | 'A2' | 'B1';
  example?: string;
  hint?: string;
  tags?: string[];
}

export const SEED_PHRASES: SeedPhrase[] = [
  // --- Личное представление ---
  {
    english: 'My name is Miras.',
    russian: 'Меня зовут Мирас.',
    category: 'everyday',
    cefrLevel: 'A1',
    example: 'Hello! My name is Miras. Nice to meet you.',
    hint: 'май нэйм из мирАс',
    tags: ['introduction'],
  },
  {
    english: 'I live in Astana.',
    russian: 'Я живу в Астане.',
    category: 'everyday',
    cefrLevel: 'A1',
    example: 'I live in Astana, the capital of Kazakhstan.',
    hint: 'ай лив ин астанА',
    tags: ['introduction'],
  },
  {
    english: 'I am married.',
    russian: 'Я женат.',
    category: 'family',
    cefrLevel: 'A1',
    example: 'I am married and I have a family.',
    hint: 'ай эм мЭрид',
    tags: ['introduction', 'family'],
  },
  {
    english: 'I have two children.',
    russian: 'У меня двое детей.',
    category: 'family',
    cefrLevel: 'A1',
    example: 'I have two children — a son and a daughter.',
    hint: 'ай хэв ту чИлдрен',
    tags: ['family'],
  },
  {
    english: 'I work as a compliance officer.',
    russian: 'Я работаю комплаенс-офицером.',
    category: 'work',
    cefrLevel: 'A2',
    example: 'I work as a compliance officer at a national holding company.',
    hint: 'ай уорк эз э комплАйенс Офисэр',
    tags: ['introduction', 'work'],
  },
  {
    english: 'I enjoy reading books.',
    russian: 'Мне нравится читать книги.',
    category: 'everyday',
    cefrLevel: 'A1',
    example: 'In my free time I enjoy reading books.',
    hint: 'ай энджОй рИдинг букс',
    tags: ['hobbies'],
  },
  {
    english: 'I like playing FIFA on PlayStation.',
    russian: 'Я люблю играть в FIFA на PlayStation.',
    category: 'everyday',
    cefrLevel: 'A1',
    example: 'In the evening I like playing FIFA on PlayStation with my son.',
    hint: 'ай лайк плЭинг фИфа он плейстЭйшн',
    tags: ['hobbies'],
  },

  // --- Исправленные фразы из диагностики ---
  {
    english: 'I am a compliance officer.',
    russian: 'Я — комплаенс-офицер.',
    category: 'work',
    cefrLevel: 'A2',
    example: 'I am a compliance officer, so I review policies every week.',
    hint: 'ай эм э комплАйенс Офисэр',
    tags: ['corrected', 'introduction'],
  },
  {
    english: 'I work in the compliance field.',
    russian: 'Я работаю в сфере комплаенса.',
    category: 'work',
    cefrLevel: 'A2',
    example: 'I have worked in the compliance field for five years.',
    hint: 'ай уорк ин зэ комплАйенс филд',
    tags: ['corrected', 'work'],
  },
  {
    english: 'Yesterday I was at home and played with my children.',
    russian: 'Вчера я был дома и играл с детьми.',
    category: 'everyday',
    cefrLevel: 'A2',
    example: 'Yesterday I was at home and played with my children all evening.',
    hint: 'йЕстэдэй ай уоз эт хоум энд плейд уиз май чИлдрен',
    tags: ['corrected', 'past-simple'],
  },
  {
    english: 'After that, we went for a walk.',
    russian: 'После этого мы пошли гулять.',
    category: 'everyday',
    cefrLevel: 'A2',
    example: 'After that, we went for a walk in the park.',
    hint: 'Афтэ зэт уи уэнт фор э уок',
    tags: ['corrected', 'past-simple'],
  },
  {
    english: 'I want to improve my English.',
    russian: 'Я хочу улучшить свой английский.',
    category: 'career',
    cefrLevel: 'A2',
    example: 'I want to improve my English for my career.',
    hint: 'ай уонт ту импрУв май Инглиш',
    tags: ['corrected', 'goals'],
  },
  {
    english: 'English can open new career opportunities.',
    russian: 'Английский может открыть новые карьерные возможности.',
    category: 'career',
    cefrLevel: 'B1',
    example: 'English can open new career opportunities for me.',
    hint: 'Инглиш кэн Оупэн нью кэрИэ опотьЮнитиз',
    tags: ['corrected', 'goals'],
  },
  {
    english: 'I want to access more professional information.',
    russian:
      'Я хочу получить доступ к большему объёму профессиональной информации.',
    category: 'career',
    cefrLevel: 'B1',
    example: 'I want to access more professional information in English.',
    hint: 'ай уонт ту Эксэс мор профЭшнл информЭйшн',
    tags: ['corrected', 'goals'],
  },
  {
    english: 'I want to earn more money.',
    russian: 'Я хочу зарабатывать больше денег.',
    category: 'career',
    cefrLevel: 'A2',
    example: 'I want to earn more money for my family.',
    hint: 'ай уонт ту эрн мор мАни',
    tags: ['corrected', 'goals'],
  },
  {
    english: 'How does your company assess compliance risks?',
    russian: 'Как ваша компания оценивает комплаенс-риски?',
    category: 'compliance',
    cefrLevel: 'B1',
    example: 'How does your company assess compliance risks every year?',
    hint: 'хАу даз ёр кАмпани эсЭс комплАйенс рискс',
    tags: ['corrected', 'questions'],
  },

  // --- Профессиональные фразы ---
  {
    english: 'identify a compliance risk',
    russian: 'выявить комплаенс-риск',
    category: 'risk',
    cefrLevel: 'B1',
    example: 'First, we identify a compliance risk in the process.',
    hint: 'айдЭнтифай э комплАйенс риск',
    tags: ['professional', 'risk'],
  },
  {
    english: 'assess a risk',
    russian: 'оценить риск',
    category: 'risk',
    cefrLevel: 'A2',
    example: 'We assess a risk before we accept it.',
    hint: 'эсЭс э риск',
    tags: ['professional', 'risk'],
  },
  {
    english: 'mitigate a risk',
    russian: 'снизить риск',
    category: 'risk',
    cefrLevel: 'B1',
    example: 'Our team works hard to mitigate a risk of corruption.',
    hint: 'мИтигейт э риск',
    tags: ['professional', 'risk'],
  },
  {
    english: 'monitor recommendations',
    russian: 'мониторить выполнение рекомендаций',
    category: 'compliance',
    cefrLevel: 'B1',
    example: 'I monitor recommendations from the last audit.',
    hint: 'мОнитэ рекомендЭйшнс',
    tags: ['professional'],
  },
  {
    english: 'implement recommendations',
    russian: 'внедрить рекомендации',
    category: 'compliance',
    cefrLevel: 'B1',
    example: 'The departments must implement recommendations on time.',
    hint: 'Имплемент рекомендЭйшнс',
    tags: ['professional'],
  },
  {
    english: 'prevent corruption',
    russian: 'предотвращать коррупцию',
    category: 'anticorruption',
    cefrLevel: 'B1',
    example: 'Our main goal is to prevent corruption in the company.',
    hint: 'привЭнт корАпшн',
    tags: ['professional', 'anti-corruption'],
  },
  {
    english: 'disclose a conflict of interest',
    russian: 'раскрыть конфликт интересов',
    category: 'compliance',
    cefrLevel: 'B1',
    example: 'Every employee must disclose a conflict of interest.',
    hint: 'дисклОуз э кОнфликт ов Интрэст',
    tags: ['professional', 'conflict-of-interest'],
  },
  {
    english: 'conduct an internal investigation',
    russian: 'провести внутреннее расследование',
    category: 'compliance',
    cefrLevel: 'B1',
    example: 'We conduct an internal investigation after every incident.',
    hint: 'кондАкт эн интЁрнл инвестигЭйшн',
    tags: ['professional'],
  },
  {
    english: 'submit a report',
    russian: 'представить отчёт',
    category: 'meetings',
    cefrLevel: 'A2',
    example: 'I submit a report to my manager every quarter.',
    hint: 'сабмИт э рипОрт',
    tags: ['professional'],
  },
  {
    english: 'review a policy',
    russian: 'рассмотреть политику',
    category: 'compliance',
    cefrLevel: 'A2',
    example: 'We review a policy once a year.',
    hint: 'ривьЮ э пОлиси',
    tags: ['professional'],
  },
  {
    english: 'approve a policy',
    russian: 'утвердить политику',
    category: 'governance',
    cefrLevel: 'A2',
    example: 'The board must approve a policy before it works.',
    hint: 'эпрУв э пОлиси',
    tags: ['professional'],
  },
  {
    english: 'comply with legal requirements',
    russian: 'соблюдать требования законодательства',
    category: 'compliance',
    cefrLevel: 'B1',
    example: 'All departments must comply with legal requirements.',
    hint: 'комплАй уиз лИгал риквАйрментс',
    tags: ['professional'],
  },
  {
    english: 'report to the board of directors',
    russian: 'отчитываться перед советом директоров',
    category: 'governance',
    cefrLevel: 'B1',
    example: 'Our compliance service reports to the board of directors.',
    hint: 'рипОрт ту зэ борд ов дайрЭкторс',
    tags: ['professional', 'governance'],
  },
  {
    english: 'take corrective action',
    russian: 'принять корректирующие меры',
    category: 'compliance',
    cefrLevel: 'B1',
    example: 'We take corrective action when we find a violation.',
    hint: 'тэйк корЭктив Экшн',
    tags: ['professional'],
  },
  {
    english: 'conduct an internal corruption risk assessment',
    russian: 'провести внутренний анализ коррупционных рисков',
    category: 'anticorruption',
    cefrLevel: 'B1',
    example: 'Every year we conduct an internal corruption risk assessment.',
    hint: 'кондАкт эн интЁрнл корАпшн риск эсЭсмент',
    tags: ['professional', 'anti-corruption'],
  },
];

export const PHRASE_CATEGORIES = [
  { id: 'everyday', ru: 'Повседневный английский' },
  { id: 'family', ru: 'Семья' },
  { id: 'work', ru: 'Работа' },
  { id: 'meetings', ru: 'Совещания' },
  { id: 'travel', ru: 'Путешествия' },
  { id: 'compliance', ru: 'Комплаенс' },
  { id: 'risk', ru: 'Управление рисками' },
  { id: 'anticorruption', ru: 'Антикоррупция' },
  { id: 'governance', ru: 'Корпоративное управление' },
  { id: 'presentations', ru: 'Презентации' },
  { id: 'emails', ru: 'Письма' },
  { id: 'career', ru: 'Карьера' },
];
